services:
  tracker-kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: tracker-kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@tracker-kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://tracker-kafka:9092,CONTROLLER://tracker-kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://tracker-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: tracker-kafka-cluster-0001
    volumes:
      - /opt/devsogu/apps/tracker-kafka/data:/var/lib/kafka/data
    networks:
      - devsogu-net

networks:
  devsogu-net:
    external: true
