// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Tracker.Infrastructure.Persistence;

#nullable disable

namespace Tracker.Infrastructure.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    [Migration("20260724020006_VehiculosViajesYConciliacion")]
    partial class VehiculosViajesYConciliacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tracker")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tracker.Domain.Entities.AsignacionDispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DesdeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("HastaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ux_asignacion_device_abierta")
                        .HasFilter("[HastaUtc] IS NULL");

                    b.HasIndex("VehiculoId")
                        .HasDatabaseName("ix_asignacion_vehiculo");

                    b.HasIndex("DeviceId", "DesdeUtc")
                        .HasDatabaseName("ix_asignacion_device_desde");

                    b.ToTable("AsignacionesDispositivo", "tracker");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.BandaHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Banda")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("DiaTipo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time(0)");

                    b.Property<Guid>("PorticoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("PorticoId", "DiaTipo")
                        .HasDatabaseName("IX_BandaHorario_Portico_Dia");

                    b.ToTable("BandasHorario", "tracker");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.GpsFix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AccuracyM")
                        .HasColumnType("float")
                        .HasColumnName("accuracy_m");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("device_id");

                    b.Property<double?>("HeadingDeg")
                        .HasColumnType("float")
                        .HasColumnName("heading_deg");

                    b.Property<long>("KafkaOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("kafka_offset");

                    b.Property<int>("KafkaPartition")
                        .HasColumnType("int")
                        .HasColumnName("kafka_partition");

                    b.Property<string>("KafkaTopic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("kafka_topic");

                    b.Property<double>("Lat")
                        .HasColumnType("float")
                        .HasColumnName("lat");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasColumnName("location");

                    b.Property<double>("Lon")
                        .HasColumnType("float")
                        .HasColumnName("lon");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<double?>("SpeedKph")
                        .HasColumnType("float")
                        .HasColumnName("speed_kph");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("datetime2")
                        .HasColumnName("utc");

                    b.Property<Guid?>("ViajeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("viaje_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Utc")
                        .HasDatabaseName("ix_gpsfix_device_utc");

                    b.HasIndex("ViajeId", "Utc")
                        .HasDatabaseName("ix_gpsfix_viaje_utc")
                        .HasFilter("[viaje_id] IS NOT NULL");

                    b.HasIndex("KafkaTopic", "KafkaPartition", "KafkaOffset")
                        .IsUnique()
                        .HasDatabaseName("ux_gpsfix_kafka_position");

                    b.ToTable("gps_fix", "tracker");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Portico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autopista")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CallesRef")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<LineString>("Corredor")
                        .HasColumnType("geography");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("LongitudKm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<long?>("OsmId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("Sentido")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Point>("Ubicacion")
                        .HasColumnType("geography");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OsmId")
                        .IsUnique()
                        .HasFilter("[OsmId] IS NOT NULL");

                    b.HasIndex("Autopista", "Codigo", "Sentido");

                    b.ToTable("Porticos", "tracker");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.TarifaPortico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Banda")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal?>("LongitudKmSnapshot")
                        .HasColumnType("decimal(12,6)");

                    b.Property<Guid>("PorticoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<decimal?>("ValorFijo")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("ValorPorKm")
                        .HasColumnType("decimal(12,6)");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VigenteHasta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PorticoId", "Banda", "VigenteDesde")
                        .HasDatabaseName("IX_Tarifa_Banda_Desde");

                    b.HasIndex("PorticoId", "Categoria", "Banda", "VigenteDesde", "VigenteHasta")
                        .HasDatabaseName("IX_Tarifa_Vigencias");

                    b.ToTable("TarifasPortico", "tracker");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Transito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AutopistaSnapshot")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Banda")
                        .HasColumnType("int");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("DiaTipo")
                        .HasColumnType("int");

                    b.Property<int>("EstadoConciliacion")
                        .HasColumnType("int");

                    b.Property<double?>("ExactitudM")
                        .HasColumnType("float");

                    b.Property<DateOnly>("FechaLocal")
                        .HasColumnType("date");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("GPS");

                    b.Property<TimeOnly>("HoraLocal")
                        .HasColumnType("time");

                    b.Property<string>("PorticoCodigoSnapshot")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("PorticoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Point>("Posicion")
                        .HasColumnType("geography");

                    b.Property<decimal>("PrecioCalculado")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("SentidoSnapshot")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid?>("TarifaPorticoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VehiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ViajeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PorticoId");

                    b.HasIndex("TarifaPorticoId");

                    b.HasIndex("Utc");

                    b.HasIndex("ViajeId")
                        .HasDatabaseName("ix_transito_viaje");

                    b.HasIndex("DeviceId", "Utc");

                    b.HasIndex("PorticoId", "Utc");

                    b.HasIndex("VehiculoId", "FechaLocal")
                        .HasDatabaseName("ix_transito_vehiculo_fechalocal");

                    b.HasIndex("DeviceId", "PorticoId", "Utc")
                        .IsUnique()
                        .HasDatabaseName("ux_transito_device_portico_utc")
                        .HasFilter("[DeviceId] IS NOT NULL");

                    b.HasIndex("VehiculoId", "AutopistaSnapshot", "FechaLocal")
                        .HasDatabaseName("ix_transito_vehiculo_autopista_fecha");

                    b.ToTable("Transitos", "tracker");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Alias")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Patente")
                        .IsUnique()
                        .HasDatabaseName("ux_vehiculo_patente");

                    b.ToTable("Vehiculos", "tracker");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Viaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadFixes")
                        .HasColumnType("int");

                    b.Property<int>("CantidadTransitos")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<double>("DistanciaKm")
                        .HasColumnType("float");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaLocalInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FinUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Point>("PuntoFin")
                        .HasColumnType("geography");

                    b.Property<Point>("PuntoInicio")
                        .HasColumnType("geography");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<LineString>("RutaSimplificada")
                        .HasColumnType("geography");

                    b.Property<decimal>("TotalGasto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("VehiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Estado")
                        .HasDatabaseName("ix_viaje_abierto_device")
                        .HasFilter("[Estado] = 0");

                    b.HasIndex("VehiculoId", "FechaLocalInicio")
                        .HasDatabaseName("ix_viaje_vehiculo_fechalocal");

                    b.HasIndex("VehiculoId", "InicioUtc")
                        .HasDatabaseName("ix_viaje_vehiculo_inicio");

                    b.ToTable("Viajes", "tracker");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.AsignacionDispositivo", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Asignaciones")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.BandaHorario", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Portico", "Portico")
                        .WithMany()
                        .HasForeignKey("PorticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portico");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.TarifaPortico", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Portico", "Portico")
                        .WithMany("Tarifas")
                        .HasForeignKey("PorticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portico");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Transito", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Portico", "Portico")
                        .WithMany()
                        .HasForeignKey("PorticoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tracker.Domain.Entities.TarifaPortico", "TarifaPortico")
                        .WithMany()
                        .HasForeignKey("TarifaPorticoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tracker.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tracker.Domain.Entities.Viaje", "Viaje")
                        .WithMany("Transitos")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Portico");

                    b.Navigation("TarifaPortico");

                    b.Navigation("Vehiculo");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Viaje", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Viajes")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Portico", b =>
                {
                    b.Navigation("Tarifas");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Vehiculo", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Viaje", b =>
                {
                    b.Navigation("Transitos");
                });
#pragma warning restore 612, 618
        }
    }
}
