// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Tracker.Infrastructure.Persistence;

#nullable disable

namespace Tracker.Infrastructure.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    partial class TrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tracker.Domain.Entities.Portico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autopista")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CallesRef")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<LineString>("Corredor")
                        .HasColumnType("geography");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("LongitudKm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sentido")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Point>("Ubicacion")
                        .HasColumnType("geography");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Autopista", "Codigo", "Sentido")
                        .IsUnique();

                    b.ToTable("Porticos", (string)null);
                });

            modelBuilder.Entity("Tracker.Domain.Entities.TarifaPortico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Banda")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<decimal?>("LongitudKmSnapshot")
                        .HasColumnType("decimal(6,3)");

                    b.Property<Guid>("PorticoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("ValorFijo")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("ValorPorKm")
                        .HasColumnType("decimal(8,3)");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VigenteHasta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PorticoId", "Banda", "VigenteDesde");

                    b.HasIndex("PorticoId", "Categoria", "Banda", "VigenteDesde", "VigenteHasta");

                    b.ToTable("TarifasPortico", (string)null);
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Transito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Banda")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<double?>("ExactitudM")
                        .HasColumnType("float");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("PorticoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Point>("Posicion")
                        .HasColumnType("geography");

                    b.Property<decimal>("PrecioCalculado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Utc");

                    b.HasIndex("PorticoId", "Utc");

                    b.ToTable("Transitos", (string)null);
                });

            modelBuilder.Entity("Tracker.Domain.Entities.TarifaPortico", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Portico", "Portico")
                        .WithMany("Tarifas")
                        .HasForeignKey("PorticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portico");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Transito", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Portico", "Portico")
                        .WithMany()
                        .HasForeignKey("PorticoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Portico");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Portico", b =>
                {
                    b.Navigation("Tarifas");
                });
#pragma warning restore 612, 618
        }
    }
}
