// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Tracker.Infrastructure.Persistence;

#nullable disable

namespace Tracker.Infrastructure.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    partial class TrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tracker")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tracker.Domain.Entities.GpsFix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AccuracyM")
                        .HasColumnType("float")
                        .HasColumnName("accuracy_m");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_utc");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("device_id");

                    b.Property<double?>("HeadingDeg")
                        .HasColumnType("float")
                        .HasColumnName("heading_deg");

                    b.Property<long>("KafkaOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("kafka_offset");

                    b.Property<int>("KafkaPartition")
                        .HasColumnType("int")
                        .HasColumnName("kafka_partition");

                    b.Property<string>("KafkaTopic")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("kafka_topic");

                    b.Property<double>("Lat")
                        .HasColumnType("float")
                        .HasColumnName("lat");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasColumnName("location");

                    b.Property<double>("Lon")
                        .HasColumnType("float")
                        .HasColumnName("lon");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<double?>("SpeedKph")
                        .HasColumnType("float")
                        .HasColumnName("speed_kph");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("datetime2")
                        .HasColumnName("utc");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Utc")
                        .HasDatabaseName("ix_gpsfix_device_utc");

                    b.HasIndex("KafkaTopic", "KafkaPartition", "KafkaOffset")
                        .IsUnique()
                        .HasDatabaseName("ux_gpsfix_kafka_position");

                    b.ToTable("gps_fix", "tracker");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Portico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autopista")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CallesRef")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<LineString>("Corredor")
                        .HasColumnType("geography");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("LongitudKm")
                        .HasColumnType("decimal(6,3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<string>("Sentido")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Point>("Ubicacion")
                        .HasColumnType("geography");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Autopista", "Codigo", "Sentido")
                        .IsUnique();

                    b.ToTable("Porticos", "tracker");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.TarifaPortico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Banda")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal?>("LongitudKmSnapshot")
                        .HasColumnType("decimal(12,6)");

                    b.Property<Guid>("PorticoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<decimal?>("ValorFijo")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("ValorPorKm")
                        .HasColumnType("decimal(12,6)");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VigenteHasta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PorticoId", "Banda", "VigenteDesde")
                        .HasDatabaseName("IX_Tarifa_Banda_Desde");

                    b.HasIndex("PorticoId", "Categoria", "Banda", "VigenteDesde", "VigenteHasta")
                        .HasDatabaseName("IX_Tarifa_Vigencias");

                    b.ToTable("TarifasPortico", "tracker");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Transito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Banda")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Banda");

                    b.Property<int>("Categoria")
                        .HasColumnType("int")
                        .HasColumnName("Categoria");

                    b.Property<double?>("ExactitudM")
                        .HasColumnType("float")
                        .HasColumnName("ExactitudM");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Fuente");

                    b.Property<Guid>("PorticoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PorticoId");

                    b.Property<Point>("Posicion")
                        .HasColumnType("geography")
                        .HasColumnName("Posicion");

                    b.Property<decimal>("PrecioCalculado")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecioCalculado");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("rowversion");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("datetime2")
                        .HasColumnName("Utc");

                    b.HasKey("Id");

                    b.HasIndex("Utc")
                        .HasDatabaseName("IX_Transitos_Utc");

                    b.HasIndex("PorticoId", "Utc")
                        .HasDatabaseName("IX_Transitos_Portico_Utc");

                    b.ToTable("Transitos", "tracker");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.TarifaPortico", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Portico", "Portico")
                        .WithMany("Tarifas")
                        .HasForeignKey("PorticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portico");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Transito", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Portico", "Portico")
                        .WithMany()
                        .HasForeignKey("PorticoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Transitos_Portico");

                    b.Navigation("Portico");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Portico", b =>
                {
                    b.Navigation("Tarifas");
                });
#pragma warning restore 612, 618
        }
    }
}
