services:
  tracker-websocket:
    image: ghcr.io/jorgedevelop2033/tracker-websocket:latest
    container_name: tracker-websocket
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DOTNET_gcServer: "0"
    ports:
      - "5137:8080"          # provisional por IP (el móvil emite aquí)
    volumes:
      - /opt/devsogu/apps/tracker-websocket/logs:/app/Logs
    mem_limit: 256m
    mem_reservation: 128m
    cpus: 0.5
    networks:
      - devsogu-net

networks:
  devsogu-net:
    external: true
